// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfppxcsfxpxumzhqbcpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcHB4Y3NmeHB4dW16aHFiY3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTExMTcsImV4cCI6MjA2NTYyNzExN30.gAxvYjDJNe-L2v_gx1dzoxxjOyHik52nHAGNiGuIXk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);